### ISSUE TITLE
Unable to access admin settings

### ISSUE THREAD

**Issue by morfab** [Legomegger/redmine_welcome_image#1]
After installing for tesing you plugin,  this fails accessing to settings configuration:

```
Started GET "/settings" for 192.168.132.175 at 2020-04-05 09:43:49 +0200
Processing by SettingsController#index as HTML
  Current user: administrador (id=1)
  Rendering settings/edit.html.erb within layouts/admin
  Rendered plugins/redmine_welcome_image/app/views/settings/_general.html.erb (4.9ms)
  Rendered common/_tabs.html.erb (6.7ms)
  Rendered settings/edit.html.erb within layouts/admin (7.0ms)
Completed 500 Internal Server Error in 67ms (ActiveRecord: 56.5ms)

ActionView::Template::Error (No route matches {:action=>"upload", :controller=>"welcome_images"}):
    36: <hr>
    37: <p>
    38:     <%= setting_label :infographics %>
    39:     <%= form_for WelcomeImage.new, url: {controller: 'welcome_images', action: 'upload'}, :html => {:multipart => true} do |f| %>                                                                                                                                        
    40:         <%= f.file_field :image, :style => 'display:inline-block'%>
    41:         <%= label_tag :display_image, l(:label_display_image)%>
    42:         <%= f.check_box :display_image %>

plugins/redmine_welcome_image/app/views/settings/_general.html.erb:39:in `_plugins_redmine_welcome_image_app_views_settings__general_html_erb__3764315299858743859_68313180'                                                                                                     
app/views/common/_tabs.html.erb:21:in `block in _app_views_common__tabs_html_erb__2529446235490805125_68610140'
app/views/common/_tabs.html.erb:20:in `each'
app/views/common/_tabs.html.erb:20:in `_app_views_common__tabs_html_erb__2529446235490805125_68610140'
app/helpers/application_helper.rb:457:in `render_tabs'
app/views/settings/edit.html.erb:5:in `_app_views_settings_edit_html_erb___3932343925460966046_68660580'
app/controllers/settings_controller.rb:33:in `index'
lib/redmine/sudo_mode.rb:64:in `sudo_mode'
```

Info about my system

```
Environment:
  Redmine version                4.1.0.devel.19521
  Ruby version                   2.4.1-p111 (2017-03-22) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.7.14
  Mercurial                      2.6.2
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.5.2
  redmine_checklists             3.1.16
  redmine_welcome_image          0.1.0
```

**Comment by huntllcx** [comment]
Same error.

If I try to open "Administration-Settings", will get "Internal Server Error", the following is details of my logfile:
```
Started GET "/settings" for 10.11.12.2 at 2020-04-08 09:32:02 +0200
Processing by SettingsController#index as HTML
  Current user: ****** (id=5)
  Rendering settings/edit.html.erb within layouts/admin
  Rendered plugins/redmine_welcome_image/app/views/settings/_general.html.erb (12.6ms)
  Rendered common/_tabs.html.erb (20.2ms)
  Rendered settings/edit.html.erb within layouts/admin (21.0ms)
Completed 500 Internal Server Error in 37ms (ActiveRecord: 4.4ms)
  
ActionView::Template::Error (No route matches {:action=>"upload", :controller=>"welcome_images"}):
    36: <hr>
    37: <p>
    38:     <%= setting_label :infographics %>
    39:     <%= form_for WelcomeImage.new, url: {controller: 'welcome_images', action: 'upload'}, :html => {:multipart => true} do |f| %>
    40:         <%= f.file_field :image, :style => 'display:inline-block'%>
    41:         <%= label_tag :display_image, l(:label_display_image)%>
    42:         <%= f.check_box :display_image %>
  
plugins/redmine_welcome_image/app/views/settings/_general.html.erb:39:in `_plugins_redmine_welcome_image_app_views_settings__general_html_erb___4385686328192273192_46912915593900'
app/views/common/_tabs.html.erb:17:in `block in _app_views_common__tabs_html_erb__2141103433239783771_46912921418400'
app/views/common/_tabs.html.erb:16:in `each'
app/views/common/_tabs.html.erb:16:in `_app_views_common__tabs_html_erb__2141103433239783771_46912921418400'
app/helpers/application_helper.rb:386:in `render_tabs'
app/views/settings/edit.html.erb:5:in `_app_views_settings_edit_html_erb___331125992255959040_46912919096000'
app/controllers/settings_controller.rb:31:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
And, this is my environments:
```
Environment:
  Redmine version                4.0.5.stable
  Ruby version                   2.5.7-p206 (2019-10-01) [x86_64-linux]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.6.11
  Git                            2.19.1
  Filesystem                     
Redmine plugins:
  redmine_custom_reminder        0.7.2.ab6adfe
  redmine_welcome_image          0.1.0
```
